Traceback (most recent call last):
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\vibhu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
p1 = pn.pane.Markdown("""
### Python popularity
""")

p2 = pn.pane.PNG("images/bg1_f1.png", width=500) 

p3= pn.pane.Markdown("""</br></br></br>

+ _Python_ has become a mainstream computing language. 
+ Details of the plot are [here](shorturl.at/htwQ7). 
+ This all means - it is good to learn to code in _Python_
""")

p4 = pn.Column(p1,p2)

pn.Row(p4, p3)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m p1 [38;5;241m=[39m [43mpn[49m[38;5;241m.[39mpane[38;5;241m.[39mMarkdown([38;5;124m"""[39m
[0;32m      2[0m [38;5;124m### Python popularity[39m
[0;32m      3[0m [38;5;124m"""[39m)
[0;32m      5[0m p2 [38;5;241m=[39m pn[38;5;241m.[39mpane[38;5;241m.[39mPNG([38;5;124m"[39m[38;5;124mimages/bg1_f1.png[39m[38;5;124m"[39m, width[38;5;241m=[39m[38;5;241m500[39m) 
[0;32m      7[0m p3[38;5;241m=[39m pn[38;5;241m.[39mpane[38;5;241m.[39mMarkdown([38;5;124m"""[39m[38;5;124m</br></br></br>[39m
[0;32m      8[0m 
[0;32m      9[0m [38;5;124m+ _Python_ has become a mainstream computing language. [39m
[0;32m     10[0m [38;5;124m+ Details of the plot are [here](shorturl.at/htwQ7). [39m
[0;32m     11[0m [38;5;124m+ This all means - it is good to learn to code in _Python_[39m
[0;32m     12[0m [38;5;124m"""[39m)

[1;31mNameError[0m: name 'pn' is not defined
NameError: name 'pn' is not defined

